import ReduxProvider from "../redux/provider";
import "./globals.css";
import { Roboto } from "next/font/google";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["300", "500"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: RootLayoutProps) {
  const bodyClasses = `${roboto.className} bg-red-700 text-white`;
  return (
    <html lang="en">
      <body className={bodyClasses}>
        <ReduxProvider>{children}</ReduxProvider>
      </body>
    </html>
  );
}

type RootLayoutProps = {
  children: React.ReactNode;
};
